coreos/tectonic-docs

Documentation/tutorials/index.md
as done by hand in
https://github.com/coreos-inc/coreos-pages/pull/1825/commits/6778db1c1124b348a3e71b0cf4d3d15a6f27146e
and
https://github.com/coreos-inc/coreos-pages/pull/1827/commits/04adce7090d6dd1c9b6cbcff819eecf199e1c081
=> tutorials/index.md: Fix links to each provider

Documentation/admin/ingress.md
please review @mauilion @coresolve @lucab
=> admin/ingress.md: correct the alignment in the doc

Documentation/admin/add-registry-cert.md
This is the same doc as: https://github.com/coreos/docs/pull/1146 with edits. This seems to be a better place for it.
=> add doc on adding self-signed registry certificate

Documentation/tutorials/sandbox/install.md
Updated broken links for installing the tectonic sandbox environment
=> docs: updated broken links

Documentation/install/rhel/installing-workers.md
=> Update the RHEL guide from customer feedback

Documentation/install/bare-metal/metal-terraform.md
Updated documentation for Terraform 0.10
=> docs: Update Bare Metal Terraform documentation

Documentation/install/bare-metal/requirements.md
not sure how you want to format the link to the changelog. please check.
=> docs: add release note link

Documentation/install/aws/aws-terraform.md, Documentation/install/azure/azure-terraform.md, Documentation/install/bare-metal/metal-terraform.md, Documentation/install/openstack/openstack-terraform.md, Documentation/install/vmware/vmware-terraform.md
Attempt to address https://twitter.com/ChrisShort/status/915658681387274242 more clearly
=> unify accessing the console instructions

Documentation/install/bare-metal/index.md
- Minor bugfix for tectonic installer directory
- Updated CoreOS versions
=> Documentation: Minor bugfix for tectonic installer directory

Documentation/install/aws/aws-terraform.md
Kyle and I found this while trying to sort something else.
=> docs: add missing command

Documentation/hack/centos-workers.md, Documentation/install/aws/aws-terraform.md, Documentation/install/aws/index.md, Documentation/install/azure/azure-terraform.md, Documentation/install/bare-metal/index.md, Documentation/install/bare-metal/metal-terraform.md, Documentation/install/openstack/openstack-terraform.md, Documentation/install/vmware/vmware-terraform.md, Documentation/troubleshooting/faq.md, Documentation/tutorials/aws/installing-tectonic.md, Documentation/tutorials/azure/install.md
* `1.7.3-tectonic.3` --> `1.7.5-tectonic.1`
* `.asc` --> `.sig`
=> Prep version string/path update for Tectonic 1.7.5-t.1

Documentation/admin/ingress.md
Update based on https://github.com/coreos/tectonic-installer/issues/2085
=> Update ELB naming and add info about Azure

Documentation/admin/logging-destination.md
Added logging infrastructure for AWS Elasticsearch [Issue#1478](https://github.com/coreos/tectonic-installer/issues/1478).
=> Added AWS ES support

Documentation/install/aws/aws-terraform.md, Documentation/install/azure/azure-terraform.md, Documentation/install/bare-metal/metal-terraform.md, Documentation/install/openstack/openstack-terraform.md, Documentation/install/vmware/vmware-terraform.md, Documentation/tutorials/aws/installing-tectonic.md, Documentation/tutorials/azure/install.md
Resolves JIRA issue [DOCS-169](https://coreosdev.atlassian.net/browse/DOCS-169).
=> Add instruction to fetch .sig file

Documentation/install/bare-metal/index.md
Upstream of the changes mocked up for staging in https://github.com/coreos-inc/coreos-pages/pull/1903
=> Doc/install/b-m/index: Add install overview video

Documentation/install/aws/uninstall.md
Completes/ref https://jira.prod.coreos.systems/browse/DOCS-95
aligns with aws/install.md
=> Doc/install/aws/uninstall: Update for tf 0.10+ without .terraformrc

Documentation/tutorials/azure/monitoring.md, Documentation/tutorials/sandbox/monitoring.md
As shipped with 1.7.x series tectonic through 1.7.5-t.1.
Ref https://jira.prod.coreos.systems/browse/DOCS-173
=> doc/tut/^(azure sandbox)/monitoring: Spec prometheus v1.7.1

Documentation/install/vmware/vmware-terraform.md
Remove the pre-alpha banner from vmware install doc.
=> install/vmware/vmware-terraform: Remove pre-alpha banner

Documentation/install/all/ddns.md
Add a new doc for using custom DNS server rather than cloud
provider DNS. Add new `install/all` directory for generic items
applicable to two or more providers.
Ref https://jira.prod.coreos.systems/browse/DOCS-61
=> Doc/install/all/ddns.md: Add DDNS configuration doc

Documentation/alm/vault-ocs.md
This breaks the docs, as this command does not work
=> vault: fix incorrect quoting

Documentation/alm/vault-ocs.md
- use new `status.nodes` format
- include anchor in next steps link
=> Update status fields

Documentation/hack/centos-workers.md, Documentation/install/aws/aws-terraform.md, Documentation/install/aws/index.md, Documentation/install/aws/uninstall.md, Documentation/install/azure/azure-terraform.md, Documentation/install/bare-metal/index.md, Documentation/install/bare-metal/metal-terraform.md, Documentation/install/openstack/openstack-terraform.md, Documentation/install/vmware/vmware-terraform.md, Documentation/troubleshooting/faq.md, Documentation/tutorials/aws/installing-tectonic.md, Documentation/tutorials/azure/install.md
Prepping for next Tectonic release: v1.8.4-tectonic.1
=> Update version strings: 1.7.9-t.2 --> 1.8.4-t.1

Documentation/troubleshooting/calico-manifests/rbac-canal-tectonic-18.yaml
Fixes https://github.com/coreos/tectonic-forum/issues/247
=> Remove unneeded yaml demarcation

Documentation/alm/prometheus-ocs.md
=> Fix Prometheus OCS Ingress URL Example

Documentation/tls/tls-kube.md
This commit ports the documentation that was originally part of
https://github.com/coreos/tectonic-installer/pull/2850.
=> Documentation/tls: add aggregated CA

Documentation/hack/centos-workers.md, Documentation/install/aws/aws-terraform.md, Documentation/install/aws/index.md, Documentation/install/aws/uninstall.md, Documentation/install/azure/azure-terraform.md, Documentation/install/bare-metal/index.md, Documentation/install/bare-metal/metal-terraform.md, Documentation/install/installer-windows.md, Documentation/install/openstack/openstack-terraform.md, Documentation/install/vmware/vmware-terraform.md, Documentation/troubleshooting/faq.md, Documentation/tutorials/aws/installing-tectonic.md, Documentation/tutorials/azure/install.md
Prep for Lithium release -- update version strings
=> Update version strings to 1.8.7-t.1

Documentation/tls/rotate-tls.md
@jmckind Let me know if the etcd section should be published or not.
=> docs: add tls rotating doc

Documentation/reference/kubelet-upgrade.md
- output the version more clearly
- get folks to cross reference with quay.io tags
=> Cross reference versions with those on quay.io

Documentation/install/rhel/installing-workers.md
@squeed Is this the recommendation we'd want to give to all users?
=> rhel: Note the Docker 1.13 IP forwarding situation

Documentation/hack/centos-workers.md, Documentation/install/aws/aws-terraform.md, Documentation/install/aws/index.md, Documentation/install/aws/uninstall.md, Documentation/install/azure/azure-terraform.md, Documentation/install/bare-metal/index.md, Documentation/install/bare-metal/metal-terraform.md, Documentation/install/installer-windows.md, Documentation/install/openstack/openstack-terraform.md, Documentation/install/vmware/vmware-terraform.md, Documentation/troubleshooting/faq.md, Documentation/tutorials/aws/installing-tectonic.md, Documentation/tutorials/azure/install.md
=> Update version strings for 1.8.4-t.4

Documentation/hack/centos-workers.md, Documentation/install/aws/aws-terraform.md, Documentation/install/aws/index.md, Documentation/install/aws/uninstall.md, Documentation/install/azure/azure-terraform.md, Documentation/install/bare-metal/index.md, Documentation/install/bare-metal/metal-terraform.md, Documentation/install/installer-windows.md, Documentation/install/openstack/openstack-terraform.md, Documentation/install/vmware/vmware-terraform.md, Documentation/troubleshooting/faq.md, Documentation/tutorials/aws/installing-tectonic.md, Documentation/tutorials/azure/install.md
=> Update version strings for 1.8.9-t.1

Documentation/account/index.md, Documentation/tutorials/index.md, Documentation/tutorials/kubernetes/watch-recovery.md
=> docs: remove sandbox references

Documentation/hack/centos-workers.md, Documentation/install/aws/aws-terraform.md, Documentation/install/aws/index.md, Documentation/install/aws/uninstall.md, Documentation/install/azure/azure-terraform.md, Documentation/install/bare-metal/index.md, Documentation/install/bare-metal/metal-terraform.md, Documentation/install/installer-windows.md, Documentation/install/openstack/openstack-terraform.md, Documentation/install/vmware/vmware-terraform.md, Documentation/troubleshooting/faq.md, Documentation/tutorials/aws/installing-tectonic.md, Documentation/tutorials/azure/install.md
Updates version strings for sync-job - Tectonic v1.7.14-tectonic.2
=> Update version strings: v1.7.14-t.2 -> v1.7.14-t.2
