Documentation/install/aws/aws-terraform.md
Documentation/install/azure/azure-terraform.md
Documentation/install/bare-metal/metal-terraform.md
Documentation/install/openstack/openstack-terraform.md
Documentation/install/vmware/vmware-terraform.md
Documentation/tutorials/aws/installing-tectonic.md
Documentation/tutorials/azure/install.md

See [DOCS-68](https://coreosdev.atlassian.net/browse/DOCS-68) on JIRA for more detail.
Adds a gpg verification step to the following docs:
* `install/aws/aws-terraform.md`
* `install/azure/azure-terraform.md`
* `install/bare-metal/metal-terraform.md`
* `install/openstack/openstack-terraform.md`
* `install/vmware/vmware-terraform.md`
* `tutorials/aws/installing-tectonic.md`
* `tutorials/azure/install.md`

Add verification for installer

---

Documentation/troubleshooting/bootkube_recovery_tool.md

There were two problems with the original command.
1. It had the archive file in the wrong position
2. The files in /var/log/containers are symlinks and so need to be dereferenced when making the archive

Dereference the container log symlinks so they are saved

---

Documentation/troubleshooting/tectonic-upgrade.md

In order to reset the state, indentation must be correct. I also changed
how the the YAML is being piped into kubectl to be less error-prone.
cc @yifan-gu

fix indentation & kubectl replace command

---

Documentation/install/aws/aws-terraform.md
Documentation/install/azure/azure-terraform.md
Documentation/install/openstack/openstack-terraform.md

Terraform 0.10 doesn't require a custom `terraformrc` file and the example was removed in https://github.com/coreos/tectonic-installer/commit/16babc9c2dcb933d45a360092e20f0b4b0fd877e. 
I didn't touch the metal docs because there's more setup required than `terraform init`.

docs: Remove terraformrc setup obsoleted with Terraform 0.10

---

Documentation/files/aws-policy.json

Terraform 0.10 requires `ec2:DescribeVpcClassicLinkDnsSupport` when describing VPCs.
https://github.com/terraform-providers/terraform-provider-aws/commit/063939ee0239fe9a3497dc32ba94f19189c0666f
```
2017/09/27 19:01:47 [ERROR] root.vpc: eval: *terraform.EvalRefresh, err: aws_vpc.new_vpc: UnauthorizedOperation: You are not authorized to perform this operation.
status code: 403, request id: 2d268ebb-f771-4475-aaa7-cecc9354438e
2017/09/27 19:01:47 [ERROR] root.vpc: eval: *terraform.EvalSequence, err: aws_vpc.new_vpc: UnauthorizedOperation: You are not authorized to perform this operation.
status code: 403, request id: 2d268ebb-f771-4475-aaa7-cecc9354438e
2017/09/27 19:01:47 [TRACE] [walkRefresh] Exiting eval tree: module.vpc.aws_vpc.new_vpc
```
```
2017-09-27T19:04:54.917Z [DEBUG] …
```

docs: Update AWS policy to allow access to ec2:DescribeVpcClassicLinkDnsSupport

---

Documentation/hack/centos-workers.md
Documentation/install/aws/aws-terraform.md
Documentation/install/aws/index.md
Documentation/install/azure/azure-terraform.md
Documentation/install/bare-metal/index.md
Documentation/install/bare-metal/metal-terraform.md
Documentation/install/openstack/openstack-terraform.md
Documentation/install/vmware/vmware-terraform.md
Documentation/troubleshooting/tectonic-upgrade.md
Documentation/tutorials/aws/installing-tectonic.md
Documentation/tutorials/azure/install.md

The release file name replaced a hyphen with an underscore between 1.7.3-t.2 and 1.7.3-t.3, viz:
tectonic-1.7.3-tectonic.2
vs
tectonic_1.73-tectonic.3

Versions strings: underscores and t.3

---

Documentation/install/rhel/installing-workers.md

Give an example command for one-time enabling the repo, and note that the service must be restarted.
Other tweaks:
- Kubelet was lowercased since it is not capitalized elsewhere.
- "Must" was changed to "should" since the cluster seems to work with workers using older hyperkube images.
- "Update" was changed to "upgrade" since Fedora has stopped documenting "update".
- "Writing" was changed to "setting" the "enabled" option to indicate that the option is already declared in the file.

Documentation/install/rhel: Be more explicit about upgrading

---

Documentation/install/aws/aws-terraform.md

Undo https://github.com/coreos/tectonic-docs/pull/63, use tf 0.10+
form, master is "1.7.5-pre"

install/aws/aws-terraform: Revert tf pre-0.10 instructions

---

Documentation/admin/logging-destination.md

Extra newline in fluentd-plugin isn't handled in our parser leading to the rest of the references being ignored.
https://coreos.com/tectonic/docs/latest/admin/logging-destination.html#prebuilt-images

Fix logging-destination reference link parsing

---

Documentation/install/azure/azure-terraform.md
Documentation/tutorials/azure/install.md

Change Azure install and tutorial doc to place deploy-time secrets
in the shell env rather than in tf config file.
Ref:
https://github.com/coreos/tectonic-installer/pull/2327
https://jira.prod.coreos.systems/browse/TECREL-126
https://jira.prod.coreos.systems/browse/DOCS-209

Azure: Move deploy secrets into environment

---

Documentation/install/aws/aws-terraform.md
Documentation/install/azure/azure-terraform.md
Documentation/install/bare-metal/metal-terraform.md
Documentation/install/openstack/openstack-terraform.md

In Unix systems, the $PATH is searched from the beginning to end.
Thereby paths mentioned first take precedence over paths mentioned
later. The shipped `terraform` binary should be choosen before a
possible locally installed `terraform` binary. This patch makes sure,
the shipped version takes precedence over any other possible local
version.
@alexsomesan @squat Please correct me if I am wrong.

Fix $PATH precedence

---

Documentation/install/aws/aws-terraform.md
Documentation/install/azure/azure-terraform.md
Documentation/install/bare-metal/metal-terraform.md
Documentation/install/openstack/openstack-terraform.md
Documentation/install/vmware/vmware-terraform.md
Documentation/tutorials/azure/install.md

For providers other than Azure, change docs to put Console user
name and password in environment. These platforms either do not have
or already store other secrets like region/loc, cloud client key, etc
in the environment.
Ref:
https://github.com/coreos/tectonic-installer/pull/2327
https://github.com/coreos/tectonic-docs/pull/92
https://jira.prod.coreos.systems/browse/TECREL-126
https://jira.prod.coreos.systems/browse/DOCS-209

install/*/*-terraform.md: Put Console secrets in environment

---

Documentation/admin/assets-zip.md
Documentation/admin/identity-management.md
Documentation/admin/index.md
Documentation/admin/ingress.md
Documentation/admin/manage-namespaces.md
Documentation/troubleshooting/faq.md
Documentation/tutorials/azure/install.md
Documentation/users/creating-accounts.md
Documentation/users/creating-roles.md

Fix a handful of broken links found with marker.
Relates to redirects added in https://github.com/coreos-inc/coreos-pages-deploy/pull/14 for Identity docs reorganization.

Documentation: Fix broken links

---

Documentation/install/aws/aws-terraform.md
Documentation/install/aws/index.md
Documentation/install/aws/uninstall.md
Documentation/install/azure/azure-terraform.md
Documentation/install/bare-metal/index.md
Documentation/install/bare-metal/metal-terraform.md
Documentation/install/openstack/openstack-terraform.md
Documentation/install/vmware/vmware-terraform.md
Documentation/tutorials/aws/installing-tectonic.md
Documentation/tutorials/azure/install.md

The installer download now expands to a
directory named
tectonic_$k8svers-tectonic.$tectonicvers
-- eg., tectonic_1.7.9-tectonic.1/
(this is the master proposed change; cherry pick from here to a new 1.7.9 tag before resync in -pages)

Extend name for expanded installer directory

---

Documentation/files/aws-policy.json

fixes: https://github.com/coreos/bugs/issues/2266 and INST-714

docs: add missing permission

---

Documentation/alm/vault-ocs.md

The pods look broken unless we tell you that the `ContainersNotReady` behavior is normal

vault: clarify container status and unseal process

---

Documentation/troubleshooting/calico-manifests/calico-upgrade-job.yaml
Documentation/troubleshooting/calico-manifests/rbac-canal-tectonic-18.yaml
Documentation/troubleshooting/tectonic-upgrade.md
Documentation/troubleshooting/upgrade-calico.md

Adds manifests for the updated RBAC rules and the migration job.
We can link to this from the release notes.

troubleshooting: add calico upgrade guide

---

Documentation/files/aws-policy.json

fixes: https://jira.coreos.com/browse/INST-855.
We update the terraform aws provider to version 1.7.0 and in this new release terraform need this permission (`s3:GetEncryptionConfiguration`)  to validate if the bucket has any encryption configurated.

docs/aws: add new permission to the policy due new aws terraform provider v1.7.0

---

Documentation/hack/centos-workers.md
Documentation/install/aws/aws-terraform.md
Documentation/install/aws/index.md
Documentation/install/aws/uninstall.md
Documentation/install/azure/azure-terraform.md
Documentation/install/bare-metal/index.md
Documentation/install/bare-metal/metal-terraform.md
Documentation/install/installer-windows.md
Documentation/install/openstack/openstack-terraform.md
Documentation/install/vmware/vmware-terraform.md
Documentation/troubleshooting/faq.md
Documentation/tutorials/aws/installing-tectonic.md
Documentation/tutorials/azure/install.md

https://github.com/coreos/tectonic-docs/pull/147/files#diff-e86b3c97e885e3003b487ad4c8366610R3
**QUESTION**: Is the above true for all versions following 1.6.4 or does it only apply to 1.6.4?

Update version strings for 1.7.14

---

Documentation/install/vmware/vmware-terraform.md
Documentation/reference/f5-ltm-lb.md

The VMware platform now uses NodePort instead of HostPort for tectonic
ingress.  This update adds instructions related to this change.
Related issue: https://github.com/coreos/tectonic-installer/issues/3080

Update docs for VMware install
